/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */

#include "CustomInputControllerTemp.h"

namespace rnoh {
using namespace facebook;

CustomInputControllerTemp::CustomInputControllerTemp(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(presentCustomInputComponent, 2),
        ARK_METHOD_METADATA(resetInput, 1),
        ARK_METHOD_METADATA(dismissKeyboard, 0),
        ARK_METHOD_METADATA(expandFullScreenForInput, 1),
        ARK_METHOD_METADATA(resetSizeForInput, 1),
    };
}

} // namespace rnoh
