
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>

namespace facebook {
namespace react {

// RNOH patch
constexpr char HighlighterViewComponentName[] = "HighlighterView";

class HighlighterViewProps : public ViewProps {
  public:
    HighlighterViewProps() = default;

    HighlighterViewProps(const PropsParserContext &context, const HighlighterViewProps &sourceProps, const RawProps &rawProps)
        : ViewProps(context, sourceProps, rawProps) {}
};

using HighlighterViewShadowNode = ConcreteViewShadowNode<
    HighlighterViewComponentName,
    HighlighterViewProps,
    ViewEventEmitter>;

class HighlighterViewComponentDescriptor final
    : public ConcreteComponentDescriptor<HighlighterViewShadowNode> {
  public:
    HighlighterViewComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};

} // namespace react
} // namespace facebook
