
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>

namespace facebook {
namespace react {

// RNOH patch
constexpr char KeyboardTrackingViewTempArkTSComponentName[] = "KeyboardTrackingViewTempArkTS";

class KeyboardTrackingViewTempArkTSProps : public ViewProps {
  public:
    KeyboardTrackingViewTempArkTSProps() = default;

    KeyboardTrackingViewTempArkTSProps(const PropsParserContext &context, const KeyboardTrackingViewTempArkTSProps &sourceProps, const RawProps &rawProps)
        : ViewProps(context, sourceProps, rawProps) {}
};

using KeyboardTrackingViewTempArkTSShadowNode = ConcreteViewShadowNode<
    KeyboardTrackingViewTempArkTSComponentName,
    KeyboardTrackingViewTempArkTSProps,
    ViewEventEmitter>;

class KeyboardTrackingViewTempArkTSComponentDescriptor final
    : public ConcreteComponentDescriptor<KeyboardTrackingViewTempArkTSShadowNode> {
  public:
    KeyboardTrackingViewTempArkTSComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};

} // namespace react
} // namespace facebook
