/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */

#include "KeyboardTrackingViewTempManager.h"

namespace rnoh {
using namespace facebook;

KeyboardTrackingViewTempManager::KeyboardTrackingViewTempManager(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(getNativeProps, 1),
        ARK_METHOD_METADATA(scrollToStart, 1),
    };
}

} // namespace rnoh
