import * as AndroidIOSComponent from 'react-native-ui-lib';
import * as HarmonyComponent from './index.harmony';
import { Platform } from 'react-native';

const isIosAndroid = Platform.OS === 'ios' || Platform.OS === 'android';

const exportComp: any = isIosAndroid ? AndroidIOSComponent : HarmonyComponent;

export const {
    Assets,
    EmojisAssetsType,
    Colors,
    DesignTokens,
    DesignTokensDM,
    Scheme, 
    SchemeType, 
    Schemes, 
    SchemeChangeListener,
    Typography, 
    TypographyKeys,
    BorderRadiuses,
    Shadows,
    Spacings,
    ComponentsColors,
    Components,
    ThemeManager,
    ColorName,
    Dividers,
    DynamicFonts,
    FontExtension,
    HighlighterOverlayView,
    SafeAreaSpacerView,
    SafeAreaInsetsManager,
    Keyboard,
    KeyboardTrackingViewProps,
    KeyboardAccessoryViewProps,
    asBaseComponent,
    Config,
    Constants,
    forwardRef,
    withScrollEnabler,
    WithScrollEnablerProps,
    withScrollReached,
    WithScrollReachedProps,
    UIComponent,
    BaseComponentInjectedProps,
    ForwardRefInjectedProps,
    ContainerModifiers,
    MarginModifiers,
    PaddingModifiers,
    TypographyModifiers,
    ColorsModifiers,
    BackgroundColorModifier,
    BaseComponent, 
    PureBaseComponent,
    ExpandableOverlayProps,
    ExpandableOverlayMethods,
    ToastProps,
    ToastPresets,
    PanViewProps,
    PanViewDirections,
    PanViewDismissThreshold,
    LogService,
    Incubator, 
    Hooks, 
    Modifiers,
    /* ===== Components ===== */
    ActionBar,
    ActionBarProps,
    ActionSheet,
    AnimatedImage,
    AnimatedScanner,
    Avatar,
    AvatarProps,
    AvatarHelper,
    Profiler,
    Badge,
    BadgeProps,
    BaseInput,
    Button,
    ButtonProps,
    ButtonSize, ButtonAnimationDirection,
    Card, CardProps, CardSectionProps, CardSelectionOptions,
    Carousel, CarouselProps, PageControlPosition,
    Checkbox, CheckboxProps, CheckboxRef,
    ChipsInput, ChipsInputProps, ChipsInputChipProps,
    Chip, ChipProps,
    ColorPicker, ColorPickerProps,
    ColorPalette, ColorPaletteProps,
    ColorPickerDialog, ColorPickerDialogProps,
    ColorSwatch, ColorSwatchProps, ColorInfo,
    ConnectionStatusBar, ConnectionStatusBarProps,
    Dash, DashProps,
    DateTimePicker, DateTimePickerProps, DateTimePickerMode,
    Dialog, DialogProps, DialogDirections, DialogDirectionsEnum,
    Drawer, DrawerProps, DrawerItemProps,
    ExpandableSection, ExpandableSectionProps,
    Fader, FaderProps, FaderPosition,
    FeatureHighlight, FeatureHighlightProps,
    FloatingButton, FloatingButtonProps, FloatingButtonLayouts,
    Gradient, GradientProps, GradientTypes,
    Slider,
    GradientSlider,
    ColorSliderGroup,
    SliderProps, GradientSliderProps, ColorSliderGroupProps,
    GridListItem, GridListItemProps,
    GridList, GridListProps,
    GridView, GridViewProps,
    HapticService, HapticType,
    Hint, HintProps,
    Icon, IconProps,
    Image, ImageProps,
    KeyboardAwareScrollView,
    KeyboardAwareFlatList,
    ListItem, ListItemProps,
    LoaderScreen, LoaderScreenProps,
    MaskedInput, MaskedInputProps,
    Marquee, MarqueeDirections, MarqueeProps,
    Modal, ModalProps, ModalTopBarProps,
    NumberInput, NumberInputProps, NumberInputData,
    Overlay, OverlayTypes,
    PageControl, PageControlProps,
    PanDismissibleView,
    PanDismissibleViewProps,
    DismissibleAnimationProps,
    PanGestureView, PanGestureViewProps,
    PanListenerView, PanListenerViewProps,
    PanningContext,
    PanningProvider,
    PanningDirections,
    PanLocationProps,
    PanAmountsProps,
    PanDirectionsProps,
    PanResponderView, PanResponderViewProps,
    asPanViewConsumer,
    Picker,
    PickerProps,
    PickerItemProps,
    PickerValue,
    PickerModes,
    PickerFieldTypes,
    PickerSearchStyle,
    RenderCustomModalProps,
    PickerItemsListProps,
    PickerMethods,
    ProgressBar, ProgressBarProps,
    ProgressiveImage, ProgressiveImageProps,
    RadioButton, RadioButtonProps,
    RadioGroup, RadioGroupProps,
    RecorderProps,
    ComponentStatics,
    ScrollBar, ScrollBarProps,
    SectionsWheelPicker, SectionsWheelPickerProps,
    SegmentedControl,
    SegmentedControlProps,
    SegmentedControlItemProps,
    SharedTransition,
    SkeletonView, SkeletonViewProps,
    SortableGridList, SortableGridListProps,
    SortableList, SortableListProps, SortableListItemProps,
    StackAggregator, StackAggregatorProps,
    StateScreen, StateScreenProps,
    Stepper, StepperProps,
    Switch, SwitchProps,
    TabController,
    TabControllerProps,
    TabControllerBarProps,
    TabControllerItemProps,
    TabControllerImperativeMethods,
    Timeline,
    TimelineProps,
    TimelinePointProps,
    TimelineLineProps,
    TimelineStateTypes,
    TimelinePointTypes,
    TimelineLineTypes,
    Text, TextProps,
    TextArea,
    TextField,
    TextFieldProps,
    TextFieldMethods,
    TextFieldRef,
    TextFieldValidationMessagePosition,
    TextFieldValidationMessagePositionType,
    TextFieldMandatoryIndication,
    TextFieldValidator,
    FieldContextType,
    TextFieldValidators,
    Toast,
    TouchableOpacity, TouchableOpacityProps,
    View, ViewProps,
    Wizard,
    WizardProps,
    WizardStepProps,
    WizardStepStates,
    WizardStepConfig,
    WizardStepsConfig,
    WheelPicker,
    WheelPickerProps,
    WheelPickerItemProps,
    WheelPickerAlign,
    WheelPickerItemValue
} = exportComp;
